<strong>Você sabia que um choque elétrico pode matar?&nbsp;Aprenda a evitá-lo:</strong></p>




<p class="MsoNormal" style="MARGIN-LEFT: 36pt; TEXT-INDENT: -18pt" align="justify">1)<span style="FONT-WEIGHT: normal; FONT-SIZE: 7pt; FONT-STYLE: normal; FONT-FAMILY: Times New Roman; FONT-VARIANT: normal">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Nunca mexa na parte interna das tomadas, seja com os dedos ou com objetos (tesouras, agulhas, facas, etc.).</p>
<p class="MsoNormal" style="MARGIN-LEFT: 36pt; TEXT-INDENT: -18pt" align="justify">2)<span style="FONT-WEIGHT: normal; FONT-SIZE: 7pt; FONT-STYLE: normal; FONT-FAMILY: Times New Roman; FONT-VARIANT: normal">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Nunca deixe as crianças brincarem com as tomadas. Vede todas as tomadas com protetores especiais ou um pedaço de esparadrapo largo.</p>
<p class="MsoNormal" style="MARGIN-LEFT: 36pt; TEXT-INDENT: -18pt" align="justify">3)<span style="FONT-WEIGHT: normal; FONT-SIZE: 7pt; FONT-STYLE: normal; FONT-FAMILY: Times New Roman; FONT-VARIANT: normal">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Ao trocar lâmpadas, toque somente na extremidade do suporte (de porcelana ou plástico) e no vidro da lâmpada elétrica. Se possível, desligue a chave geral antes de fazer a troca.</p>
<p class="MsoNormal" style="MARGIN-LEFT: 36pt; TEXT-INDENT: -18pt" align="justify">4)<span style="FONT-WEIGHT: normal; FONT-SIZE: 7pt; FONT-STYLE: normal; FONT-FAMILY: Times New Roman; FONT-VARIANT: normal">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Nunca toque em aparelhos elétricos quando estiver com as mãos ou o corpo úmidos.</p>
<p class="MsoNormal" style="MARGIN-LEFT: 36pt; TEXT-INDENT: -18pt" align="justify">5)<span style="FONT-WEIGHT: normal; FONT-SIZE: 7pt; FONT-STYLE: normal; FONT-FAMILY: Times New Roman; FONT-VARIANT: normal">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Não mude a chave de temperatura&nbsp;do chuveiro elétrico com o corpo molhado e o chuveiro ligado.</p>
<p class="MsoNormal" style="MARGIN-LEFT: 36pt; TEXT-INDENT: -18pt" align="justify">6)<span style="FONT-WEIGHT: normal; FONT-SIZE: 7pt; FONT-STYLE: normal; FONT-FAMILY: Times New Roman; FONT-VARIANT: normal">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Mantenha os aparelhos elétricos em bom estado. Mande para uma oficina especializada sempre que apresentarem problemas ou causarem pequenos choques.</p>
<p class="MsoNormal" style="MARGIN-LEFT: 36pt; TEXT-INDENT: -18pt" align="justify">7)<span style="FONT-WEIGHT: normal; FONT-SIZE: 7pt; FONT-STYLE: normal; FONT-FAMILY: Times New Roman; FONT-VARIANT: normal">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Verifique sempre os fios elétricos que ficam à vista. Com o tempo, sua capa protetora se desgasta. Nunca deixe um fio elétrico descoberto.</p>
<p class="MsoNormal" style="MARGIN-LEFT: 36pt; TEXT-INDENT: -18pt" align="justify">8)<span style="FONT-WEIGHT: normal; FONT-SIZE: 7pt; FONT-STYLE: normal; FONT-FAMILY: Times New Roman; FONT-VARIANT: normal">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Instale o fio terra em chuveiros.</p>
<p class="MsoNormal" style="MARGIN-LEFT: 36pt; TEXT-INDENT: -18pt" align="justify">9)<span style="FONT-WEIGHT: normal; FONT-SIZE: 7pt; FONT-STYLE: normal; FONT-FAMILY: Times New Roman; FONT-VARIANT: normal">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Ao manusear objetos metálicos, tenha cuidado para que não esbarre em nenhum cabo elétrico aéreo.</p>
<p class="MsoNormal" style="MARGIN-LEFT: 36pt; TEXT-INDENT: -18pt" align="justify">10)<span style="FONT-WEIGHT: normal; FONT-SIZE: 7pt; FONT-STYLE: normal; FONT-FAMILY: Times New Roman; FONT-VARIANT: normal">&nbsp; </span>Nunca pise em fios caídos no chão. Principalmente se a queda foi conseqüência de uma tempestade.</p>
<p class="MsoNormal" style="MARGIN-LEFT: 36pt; TEXT-INDENT: -18pt" align="justify">11) Não sobrecarregue a rede elétrica com eletrodomésticos. Não use T (benjamim ou extensão) para ligar mais de um aparelho na mesma tomada.</p>
<p class="MsoNormal" style="MARGIN-LEFT: 36pt; TEXT-INDENT: -18pt" align="justify">12) Revise periodicamente (de preferência uma vez por ano) a rede elétrica de edifícios, apartamentos e casas para mantê-la em perfeito estado.</p>
<p class="MsoNormal" style="MARGIN-LEFT: 36pt; TEXT-INDENT: -18pt" align="justify">11)<span style="FONT-WEIGHT: normal; FONT-SIZE: 7pt; FONT-STYLE: normal; FONT-FAMILY: Times New Roman; FONT-VARIANT: normal">&nbsp; </span>Não deixe crianças empinar pipas em locais onde houver cabos elétricos                       	
